services:
  - type: web
    name: artistalley-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn artistalley.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: CORS_ALLOWED_ORIGINS
        value: https://yuvraj20gole.github.io
      - key: FRONTEND_URL
        value: https://yuvraj20gole.github.io/ArtistAlley
      - key: GOOGLE_OAUTH2_REDIRECT_URI
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: artistalley-db
          property: connectionString
    disk:
      name: artistalley-disk
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: artistalley-db
    plan: free
    databaseName: artistalley
    user: artistalley

